[package]
name = "aloroid/vide-with-types"
description = "A reactive Luau library for creating UI. This includes a massive types file to give the create function typechecking."
license = "MIT"
version = "0.2.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["default.project.json", "LICENSE", "src"]
exclude = [
    ".github",
    "docs",
	"test",
	".gitattributes",
	".gitignore",
    ".luaurc",
	"CHANGELOG.md",
	"README.md",
    "todo.md",
	"scripts"
]
